#!/bin/bash

# extract table of contents from index.html
# and delete preface link
BOOKDIR=book
gawk '
/<div class="toc">/ {
    print $0
    getline #TODO: check this is the <ul> line
    print $0
    print "<li><a href=\".\">Git Magic</a></li>"
    getline
    while (!match($0, "</div>")) {
	if (match($0, "<li><span class=\"preface\"")) {
	    while (!match($0, "</span>")) {
		getline
	    }
	    getline
	}
	print $0
	getline
    }
    print "</div>"
    exit
}
' < $BOOKDIR/index.html > toc.tmp

# for every file except the index...
for FILE in $BOOKDIR/*.html
do
    if [ $FILE != "$BOOKDIR/index.html" ]
    then
    # add "Git Magic - " to titles of all pages
    sed '/<title>/ s/<title>/&Git Magic - /' -i $FILE
    sed 's/pr01\.html/index.html/g' -i $FILE
    # paste ToC into beginning
    # and add div section with class content for CSS
    sed '/<body/{n; r toc.tmp
a <div class="content">
} ' -i $FILE
    sed '/^<\/body/i </div>' -i $FILE
    fi
done

sed '/^<\/body/i </div><div class="footer"><a href="/~blynn/">My Homepage</a></div>' -i $BOOKDIR/*.html

sed '/<\/body>/ i \
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"> \
</script> \
<script type="text/javascript"> \
_uacct = "UA-1901330-2"; \
urchinTracker(); \
</script>' -i $BOOKDIR/*.html

mv $BOOKDIR/pr01.html $BOOKDIR/index.html
rm toc.tmp
