#!/bin/bash

# Extract table of contents from index.html and delete preface link.
BOOKDIR=book-$1
TITLE="Git Magic"
case $1 in
    ru)
        TITLE="Волшебство Git"
        ;;
esac

gawk '
/<div class="toc">/ {
  print $0
  getline
  print $0
  print "<li><b>'"$TITLE"'</b></li>"
  getline
  while (!match($0, "</div>")) {
    gsub("pr01.html", "index.html")
    print $0
    getline
  }
  print $0
  exit
}
' < $BOOKDIR/index.html > toc.tmp

# For every file except the index...
for FILE in $BOOKDIR/*.html
do
  if [ $FILE != "$BOOKDIR/index.html" ]
  then
    # Prepend "Git Magic - " to titles of all pages.
    sed '/<title>/ s/<title>/&'"$TITLE"' - /' -i $FILE
    sed 's/pr01\.html/index.html/g' -i $FILE
    # Paste ToC into beginning and add div section with class content for CSS.
    sed '/<body/{n; r toc.tmp
a <div class="content">
}' -i $FILE
    sed '/^<\/body/i </div>' -i $FILE
  fi
done

# Originally this link was "My Homepage". Since it appears on translations of
# the guide, I changed it to my name so it doesn't have to be translated.
sed '/^<\/body/i </div><div class="footer"><a href="/~blynn/">Ben Lynn</a></div>' -i $BOOKDIR/*.html

cp $BOOKDIR/pr01.html $BOOKDIR/index.html
rm toc.tmp
